[package]
name = "xdl"
version = "0.1.7"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Extentional input layer on Rust-SDL2 or Rokol"
repository = "https://github.com/toyboot4e/xdl"

[features]

[dependencies]
num_enum = "0.5.1"

serde = { version = "1.0.120", features = ["derive"], optional = true }
sdl2 = { version = "^0.34.3", optional = true }
rokol = { path = "../rokol", features = ["impl-app"], optional = true, default-features = false }

