[package]
name = "xdl"
version = "0.1.3"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"
license = "MIT"
description = "An entension layer to Rust-SDL2"
# homepage
# documentation
repository = "https://github.com/toyboot4e/xdl"
# readme

[dependencies]
# TODO: use semvar
sdl2 = "0.34.3"
num_enum = "0.5.1"
